### ISSUE TITLE
When using windows Damomine i get an error message.  see screenshot below. 

### ISSUE THREAD

**Issue by Minerdudeshannon** [damomine/aleominer#11]
When using windows Damomine i get an error message.  I think it has something to do with my RTX 4090 as i dont have this issue on my other rigs.
![errors](https://user-images.githubusercontent.com/120304756/206895630-db1cd901-fde7-48fe-8901-c1ee0994bf91.jpg)

**Comment by KaptinLin** [comment]
we are going to support 4090 in the upcoming releases.

**Comment by Minerdudeshannon** [comment]
No worries.
