### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by huydq-eth** [damomine/aleominer#12]
> 12-11 15:36:51  INFO                                                  
12-11 15:36:51  INFO               _                                  
12-11 15:36:51  INFO              | |                                 
12-11 15:36:51  INFO            __| | __ _   _ __ ___   ___           
12-11 15:36:51  INFO           / _` |/ _` | | '_ ` _ \ / _ \          
12-11 15:36:51  INFO          | (_| | (_| | | | | | | | (_) |         
12-11 15:36:51  INFO           \__,_|\__,_| |_| |_| |_|\___/          
12-11 15:36:51  INFO                                                  
12-11 15:36:51  INFO                     Damo miner                    
12-11 15:36:51  INFO                       2.0.0                       
12-11 15:36:51  INFO                                                  
12-11 15:36:51  INFO ------------------ System info ------------------
12-11 15:36:51  INFO OS:      RAVEOS 1.0.26, 5.10.27-mining-mod
12-11 15:36:51  INFO CPU:     Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
12-11 15:36:51  INFO RAM:     46390 MB / 48108 MB
12-11 15:36:51  INFO CUDA:    Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
12-11 15:36:51  INFO -------------------------------------------------
12-11 15:36:51  INFO ------------------ Config info ------------------
12-11 15:36:51  INFO ADDRESS: aleo17nnlhzevuxp7zju29p43yxz02pujdm667c2cp8a5xczqalamyv9qafve6l
12-11 15:36:51  INFO POOL:    asiahk.damominer.hk:9090
12-11 15:36:51  INFO -------------------------------------------------
12-11 15:36:51  INFO ------------------ Device info ------------------
12-11 15:36:51  INFO |ID|PCI| Memory| MaxTemp|                        
12-11 15:36:51  INFO | 0|  3|  8192M|      93| NVIDIA GeForce RTX 3070
12-11 15:36:51  INFO -------------------------------------------------
12-11 15:36:57  INFO Start working
Segmentation fault

======================================================================
My driver:

> root@hoa41:/app-data/miners/damominer-2.0.0# nvidia-smi
Sun Dec 11 15:42:57 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.11    Driver Version: 525.60.11    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:03:00.0  On |                  N/A |
| 35%   59C    P0    52W / 220W |     11MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       457      G   X                                   9MiB |
+-----------------------------------------------------------------------------+

**GPU: NVIDIA GeForce RTX 3070**
Could you help me check this issue? Many thanks

**Comment by KaptinLin** [comment]
you can try new damominer in the release page

**Comment by meuccibear** [comment]
![image](https://user-images.githubusercontent.com/44260329/207219659-83a70d02-13b5-4e01-82f4-7b6ed32808f3.png)
Could you help me check this issue? Many thanks

**Comment by KaptinLin** [comment]
you can reinstall nvidia drive and try again.
