### ISSUE TITLE
ERROR Disconnected from proxy

### ISSUE THREAD

**Issue by GMND** [damomine/aleominer#17]
aleo1.damominer.hk
aleo2.damominer.hk
aleo3.damominer.hk
asiahk.damominer.hk

![изображение](https://user-images.githubusercontent.com/26802919/208224694-89aa9a5a-c051-4029-bf5b-7d0af9f1021e.png)

**Comment by KaptinLin** [comment]
Thanks for reporting. Which location you are?

**Comment by GMND** [comment]
![изображение](https://user-images.githubusercontent.com/26802919/208628685-f687d6be-19bc-408b-bc4a-58bbefd8e836.png)

**Comment by KaptinLin** [comment]
damominer will release European proxy line soon
