### ISSUE TITLE
Relentless memory allocation error 2.2.4

### ISSUE THREAD

**Issue by supasnipa360** [damomine/aleominer#19]
Version 2.2.4 begins running for between 10 and 30 seconds, before spitting out error "memory allocation of 1277952 bytes failed". This is happening with varied hardware (1x 5950x amd cpu and 1x 3950x amd cpu). 16 cores and 8x to 16x pcie lanes per gpu device. GPUs in these instances include, 3080tis, 3090s and a 3090ti.

**Comment by KaptinLin** [comment]
Can you try reboot windows and try again?
The devs will look into this issue.

**Comment by KaptinLin** [comment]
If still not working, you can try increase your visual memory.

https://www.windowscentral.com/how-change-virtual-memory-size-windows-10

**Comment by supasnipa360** [comment]
That nailed it (Increasing Virtual Memory). Currently succeeding with 4096-6148 for 3 RTX 3090 GPU configuration.
