### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoDevice', src\main.rs:255:49

### ISSUE THREAD

**Issue by hust-zXX** [damomine/aleominer#20]
It has been running fine for half a month, but after I restart the computer, the following problem occurs.Damo GPU Miner for Aleo Windows V2.2.4. 

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoDevice', src\main.rs:255:49

This issue also existed in earlier versions.

**Comment by KaptinLin** [comment]
Can you reinstall nvidia driver and see if works?
