### ISSUE TITLE
Issue for both 2.3.0 and 2.3.1

### ISSUE THREAD

**Issue by mxylyf** [damomine/aleominer#21]
I'm using win10 with 64g RAM, GPU 3080 and 3080ti, when I start mine, it will auto stop after half mins, I don't konw where to check error logs, this issue only exist in my windows platform, for both 1920x 2687v3 5900x. But it doesn't happend in my linux platform.

**Comment by mxylyf** [comment]
I already set virtual memory up to 36gb for two 3080 platform, also meet this issue.
01-07 20:04:16  INFO POOL:    aleo2.damominer.hk:9090
01-07 20:04:16  INFO -------------------------------------------------
01-07 20:04:16  INFO ------------------ Device info ------------------
01-07 20:04:16  INFO |ID|PCI| Memory| MaxTemp|
01-07 20:04:16  INFO | 0|  2| 10240M|      93| NVIDIA GeForce RTX 3080
01-07 20:04:16  INFO | 1|  3| 10240M|      93| NVIDIA GeForce RTX 3080
01-07 20:04:16  INFO -------------------------------------------------
01-07 20:04:23  INFO Start working
01-07 20:04:23  INFO Received a new epoch challenge (1394)

C:\Users\Desktop\damominer_win_v2.3.0>pause

**Comment by GrafDracula1** [comment]
hello, I have the same problem, the same parameters, windows 10 cpu i9 9900kf, 64 gb,rtx 3080

**Comment by leanlp** [comment]
I had a similar problem and solved it by installing driver version 516.94. Good luck.

**Comment by mxylyf** [comment]
I tried 516.94 and 528.02 still have this issue.

**Comment by rainylane** [comment]
me too.
win10 10700k rtx3080 32gb
version 472 511 512 516 526 527 528

**Comment by KaptinLin** [comment]
we'll release 2.3.2 that fix the issue soon.

**Comment by KaptinLin** [comment]
https://github.com/damomine/aleominer/releases/tag/v2.3.2

**Comment by rainylane** [comment]
&nbsp; &nbsp; &nbsp;Damo miner&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;2.3.2
OS:&nbsp; &nbsp; &nbsp; Windows 10.0.17763 (Workstation), 17763
CPU:&nbsp; &nbsp; &nbsp;Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz, 16 threads
RAM:&nbsp; &nbsp; &nbsp;28848 MB / 32578 MB


C:\damominer_win_v2.3.2&gt;pause


version 472.84、511.09、512.15、516.94、526.98、527.41、528.02
