### ISSUE TITLE
Issue for both 2.3.0 and 2.3.1

### ISSUE THREAD

**Issue by AlexSuvorov2k** [damomine/aleominer#22]
Win 10, 64Gb RAM, GPU 6700XT

thread 'main' panicked at 'Failed to initialize nvml: LibloadingError(LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "Не найден указанный модуль." } })', src\environment\mod.rs:41:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by KaptinLin** [comment]
hi, you can reinstall the latest nvidia driver. https://www.nvidia.com/download/index.aspx

**Comment by KaptinLin** [comment]
See https://github.com/damomine/aleominer/releases/tag/v2.3.2

**Comment by AlexSuvorov2k** [comment]
But i have AMD 6700XT
