### ISSUE TITLE
RTX3080 wrong

### ISSUE THREAD

**Issue by rainylane** [damomine/aleominer#23]
Damo miner           2.3.2
OS:      Windows 10.0.17763 (Workstation), 17763
CPU:     Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz, 16 threads
RAM:     28848 MB / 32578 MB

C:\damominer_win_v2.3.2>pause

version 472.84、511.09、512.15、516.94、526.98、527.41、528.02

**Comment by KaptinLin** [comment]
thanks for reporting. we'll look into this later

**Comment by iaries77** [comment]
I am also i7-10700KF, the same is pause, now I can only use 2.24

**Comment by Canefis** [comment]
Hashrate is very low!!!

**Comment by KaptinLin** [comment]
you can try 2.3.4

**Comment by rainylane** [comment]
C:\damominer_win_v2.3.4>pause
version 472.84 511.09 516.94 522.25 526.98 527.41 528.02
 I can only use v2.2.4

**Comment by KaptinLin** [comment]
2.3.5 may works
