### ISSUE TITLE
No WSL Support 

### ISSUE THREAD

**Issue by ZKSYNCDEV** [damomine/aleominer#4]
Gtk-WARNING **: : cannot open display: :0 please allow to work on servers without display port attached. thx

**Comment by KaptinLin** [comment]
you can try with wsl2 on win11

**Comment by huukhoa1412** [comment]
My computer dont can run win11

**Comment by KaptinLin** [comment]
now have windows support, you can go to [releases page](https://github.com/damomine/aleominer/releases) download the package, and give a try
